# Generated by Django 5.1.2 on 2024-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=10)),
                ('gender', models.CharField(max_length=200)),
                ('medical_issue', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(max_length=200)),
                ('appointment_date', models.DateField(auto_now_add=True)),
                ('appt_time', models.TimeField(auto_now_add=True)),
                ('mbl', models.CharField(max_length=13)),
            ],
        ),
    ]
